# Generated by Django 4.2.3 on 2023-09-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_forum_slug_post_slug_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
        ),
    ]
