# Generated by Django 3.2.4 on 2023-10-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0006_auto_20231003_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
