# Generated by Django 3.2.4 on 2023-10-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0009_auto_20231004_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=models.TextField(), max_length=200),
        ),
    ]
