# Generated by Django 5.0.2 on 2025-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0011_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar13.jpg', upload_to='avatars/'),
        ),
    ]
