# Generated by Django 5.0.2 on 2025-02-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0012_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=123, max_length=255, verbose_name='email'),
            preserve_default=False,
        ),
    ]
